### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by scopatz** [estani/ttyrec_tools#1]
Hello @estani, I am interested in using this code, but I didn't see a license.  How is it licensed?

**Comment by estani** [comment]
Sorry was away for a while. Which license will suit you best? I'll add it then.

**Comment by scopatz** [comment]
Hi @estani,  either BSD 3-clause or MIT work best for me. Thanks!

**Comment by estani** [comment]
Sorry for the delay!! MIT License added.

**Comment by scopatz** [comment]
Thanks!
